p8105_hw2_fs2968
================
2026-09-30

Importing necessary libraries

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Problem 1, NYC Transit Data

``` r
t_data = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  na = c("NA", "", ".")) |> 
  janitor::clean_names() |> 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada) |> 
  mutate(
    entry = case_match(
      entry, 
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

In the above code, we read in the NYC transit subway data-set that
includes information about the following points: line, station name,
station latitude and longitude, the route it lies on, whether there is
an entry and whether there is a fee, and the entrance type. To clean the
data, we first use the `clean_names` function from the janitor package
to ensure all of the column names are cleaned so that there are no dots,
uppercase, and overall more consistent. The next step was selecting all
of the columns that we want to keep using the `select` function applied
on the imported data. Note, since we wanted all route information, we
use the `starts_with` function to include all columns with names that
start with route to simplify the code. Lastly, we use the `mutate`
function to change the data-set, modifying the entry column to be a
logical vector with `TRUE` and `FALSE` instead of characters `"YES"` and
`"NO"`. In the import, you could consider declaring
`NA= c("NA", "", ".")` a cleaning step, but it is more of an
identification for the read_csv function of what the missing values will
be.

The post-clean data set has dim (1868, 19), which represents 1868
transit stations (rows) with 19 descriptor fields per row (columns).
After all of the cleaning, the data is mostly tidy. The names look good
and data typing is in line with normal standards, but one thing we are
missing is that some of the column names are observation values,
specifically route1,…,route11. Instead of separating these into 11
different groups, we should instead have this as one column for routes.

To find the number of distinct stations, which vary by name and line, we
can use the `distinct` and `nrow` functions:

``` r
nrow(distinct(t_data, station_name, line))
```

    ## [1] 465

To find the number of stations that are ADA compliant, we look at all
stations that are ADA compliant, and then add the `distinct` function to
ensure we aren’t double counting any stations, and then use `nrow` to
find the total.

``` r
filter(t_data, ada == TRUE) |> 
  distinct(station_name, line) |> 
  nrow()
```

    ## [1] 84

To find the number of station entrances/exits without vending that allow
entrance, we first `filter` t_data for those that allow entrance and
those without vending. Once we have that filtered data-set, we similarly
use `distinct` to make sure we aren’t repeating stations and use `nrow`
to find the total. Now we have all of the pieces and we simply divide
that value by the total number of distinct stations without vending to
find the proportion:

``` r
numerator = filter(t_data, entry == TRUE, vending == "NO") |> 
            distinct(station_name, line) |> 
            nrow()

denominator = filter(t_data, vending == "NO") |> 
              distinct(station_name, line) |> 
              nrow()

numerator/denominator
```

    ## [1] 0.4343434

To reformat the data, we will use the `pivot_longer` function to change
the route columns to describe the route number as one column and the
route name as another. Before we do that, we first need to change the
route names to all be char because route 1,2,3,4,… are default to
doubles:

``` r
reformatted_t_data = 
  t_data |> 
  mutate(
    across(starts_with("route"), as.character)
  ) |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

Now we can answer the find the number of distinct stations that serve
the A train by using the `filter` function to only look at stations that
serve the A, and then use the `distinct` and `nrow` functions to find
the total distinct stations:

``` r
filter(reformatted_t_data, route_name == "A") |> 
  distinct(station_name, line) |> 
  nrow()
```

    ## [1] 60

To further find the number that are ADA compliant, we simply add that to
the previous `filter` function:

``` r
filter(reformatted_t_data, route_name == "A", ada == TRUE) |> 
  distinct(station_name, line) |> 
  nrow()
```

    ## [1] 17

## Problem 2, Trash Wheel Dataset

We first read in the Trash Wheel Data-set and remove non-data entries
and not including dumpster specific data. We also can adjust the names
to be more reasonable and round the number of sports balls to the
nearest integer and convert to an integer type using `as.integer`.

``` r
trash_data = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx", 
    sheet="Mr. Trash Wheel", 
    range="A2:N742",
    na = c("NA", "", ".")) |> 
  janitor::clean_names() |> 
  mutate(
    across(sports_balls, round),
    across(sports_balls, as.integer),
    owner = "Mr. Trash",
    across(year, as.double)
  )
```

Now we can grab the other two datasets and clean them using a similar
process:

``` r
prof_data = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx", 
    sheet="Professor Trash Wheel", 
    range="A2:M139",
    na = c("NA", "", ".", "dive"))|> 
  janitor::clean_names() |> 
  mutate(
    owner = "Professor Trash",
    )

gwyn_data = 
  readxl::read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx", 
    sheet="Gwynnda the Good Wheel of the W", 
    range="A2:L394",
    na = c("NA", "", "."))|> 
  janitor::clean_names() |> 
  mutate(owner = "Gwynns Trash")
```

Now we can use the `bind_rows` function to join these data-sets
together. Before that, we can create a column in all three called
“owner”, which designates who the data comes from, editted in the above
code blocks.

``` r
total_trash = bind_rows(trash_data, prof_data, gwyn_data)
```

The resulting data-set `total_trash` is the combination of all three
excel sheets. This combined data-set includes 1269 observations (rows)
and 15 variables (columns). There are both identification variables and
descriptive variables. The identification variables include dumpster,
month, year, date, which help us identify the dumpsters and when the
were observed. The descriptive variables include weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered,
owner, which describe the weight, volume, and breakdown of what is found
in the dumpster. The weight is measured in tons with mean value of
3.0623168, and the volume is measured in cubic yards with an mean value
of 15.0133964. The other descriptive variables that detail what actual
items are in the dumpters use integer interpretations, for example, the
first 3 dumpsters had 584, 496, 1080 plastic bags.

For the available data, the total weight of trash collected by Professor
Trash Wheel was 3886.08 tons. We can additionally find the total number
of cigarette butts collected by Gwynnda in June of 2022 as 1.812^{4}.

## Problem 3, Alzheimer’s Disease Dataset

First, we need to import, clean, and tidy the dataset.

``` r
a_data = 
  read_csv("data/data_mci/MCI_baseline.csv",
           na = c("NA", ".", ""),
           skip= 1
           ) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex, 
      1 ~ "Male",
      0 ~ "Female"
    ),
    apoe4 = case_match(
      apoe4,
      1 ~ TRUE,
      0 ~ FALSE
    )
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#We don't include the filter in the a_data because we need to describe the number of people filtered out later
a_valid_data = filter(a_data, !current_age > age_at_onset | is.na(age_at_onset))
```

We import our dataset with the usual `read_csv` function and mark “NA”,
“.”, and “” as the potential na values. Taking a look at the data, it
seems like . is the used na value. Next, we use clean names to make sure
the names are consistent and easy to use, then we use the mutate
function to change the sex variable to characters “Male” and “Female”
and change the APOE4 gene variables to `TRUE` and `FALSE` since it
designates whether that gene is present. Lastly, we removed any
participants who had an age of onset prior to the baseline using the
`filter` function. Note, we include those with na values for age of
onset since those are participants who were in the study to not develop
MCI during the study.

For relevant features of the dataset, there are 480 valid participants
(rows) and 6 variables per participant. These variables include id,
current_age, sex, education, apoe4, age_at_onset, which help describe
participants risk of developing MCI given age, education, sex, and
presence of the APEO4 gene. In total, there were 483 participants
recruited, but since 3 participants had MCI at baseline, we only include
480 participants in our analysis. Of these valid participants, 94
developed MCI during the study and follow-up period. The average
baseline age is 65.0320833 and 43.75 percent of the study is women
participants, and 30 percent of women in the study are APOE4 carriers.

Next, we can import the biomarker dataset.

``` r
b_data = 
  read_csv("data/data_mci/mci_amyloid.csv",
           skip = 1,
           na = c("NA", "Na")) |> 
  janitor::clean_names() |> 
  rename(time_0 = baseline) |> 
  pivot_longer(
    time_0:time_8,
    names_to = "years_elapsed",
    names_prefix = "time_",
    values_to = "amyloid_ratio"
  ) |> 
  mutate(
    across(years_elapsed, as.double),
    across(amyloid_ratio, as.double)
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

First, we import the data, skip the first row since its descriptive and
not relevant, and mark “NA” and “Na” as the missing value. Then we can
clean names to make them consistent and easy to use. Next, we can look
at our data and see that the column names study_id, years_elapsed,
amyloid_ratio, NA, NA are observed values, where the baseline and
biomarker measurements are described as “Time (in years) elapsed since
the study baseline to the visit where biomarker Amyloid \_ 42/40 ratio
was measured”. Subsequently, we use the `pivot_longer` function to
transform these into two columns, years elapsed and amyloid ratio.
Before that, we also want to change the baseline variable to time_0, so
it aligns with the other column names that we want to transform. Lastly,
we change the all values from characters to doubles so that they are
mathematically interpretable.

The cleaned dataset has 2435 participants (rows) with study_id,
years_elapsed, amyloid_ratio as the data points we have for each
participants (cols). For the years_elapsed column, we have values 0, 2,
4, 6, 8 for each participant, tracking the amyloid ratio through the
study. For example, we have baseline/years elapsed equal to 0 with a
mean value of 0.9958932.

Now, we can check the number of participants who appear only in the
baseline or only in the amyloid dataset. To accomplish this, we can use
the `left_join` function to join the baseline dataset to the amyloid
dataset by the id/study id variables. Once they are joined, for
participants who only appear in the baseline, we can just check if they
have NA values for the amyloid ratio, which would mean that they are not
in the amyloid dataset. We can similarly check who is only in the
Amyloid dataset by switching the order of datasets in `left_join` and
changing the criteria to whether education exists (or any other variable
in baseline dataset that does not exist in amyloid dataset).

Note, since we originally changed the amyloid dataset to have time set
as one column, there are ids with multiple instances for each elapsed
year, so here, we use the pre-pivoted dataset since there is only one
row per id. Additionally, for the participants who only were in the
amyloid dataset, we generically chose education as the field to indicate
whether someone was in the baseline dataset, so we do an additional
check at the end to make sure there were no NA values in education for
those in the baseline dataset, which results in zero.

``` r
b_data_original = 
  read_csv("data/data_mci/mci_amyloid.csv",
           skip = 1,
           na = c("NA", "Na")) |> 
  janitor::clean_names() |> 
  rename(time_0 = baseline)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unique_a =
  left_join(a_valid_data, b_data_original, by = c("id" = "study_id")) |> 
  filter(if_all(starts_with("time_"), is.na)) |> 
  distinct()

unique_b =
  left_join(b_data_original,a_valid_data , by = c("study_id" = "id")) |> 
  filter(is.na(education)) |> 
  distinct()

cat("The number of participants only in baseline dataset is", nrow(unique_a))
```

    ## The number of participants only in baseline dataset is 8

``` r
cat("The number of participants only in amyloid dataset is", nrow(unique_b))
```

    ## The number of participants only in amyloid dataset is 15

``` r
cat("The number of participants in baseline dataset with missing education is", nrow(filter(a_valid_data, is.na(education))))
```

    ## The number of participants in baseline dataset with missing education is 0

As mentioned in the output code, we can see that there are 8
participants only in the baseline dataset and 15 participants only in
the amyloid dataset. Of those only included in the baseline, only 3
developed MCI and of those only included in the amyloid dataset, only 1
did not record a baseline amyloid ratio.

Now looking at the participants who were in both baseline and amyloid
datasets, we can build the entire combined dataset and then remove those
who’s ids align with the ones we just found to not be in either dataset.
Since the `left_join` function will already remove those ids not in
baseline, all we need to do is remove those that are only in baseline
using `filter`.

``` r
combined_data = 
  left_join(a_valid_data, b_data, by = c("id" = "study_id")) |> 
  filter(!id %in% pull(unique_a, id))
```

The resulting dataset has 2360 data points (rows), where each datapoint
is a participant at a specific elapsed year, and it has 8 variables per
observation (cols). In this dataset, we have only included participants
of both the baseline and amyloid datasets. At the baseline year of those
who were measured, they have an average age of 65.05 years old and
average amyloid ratio of 0.111.

``` r
write_csv(combined_data, "data/combined_data.csv")
```
